version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      cassandra-net:
        aliases:
          - cassandra-node1
    ports:
      - "9042:9042"  # expose CQL port

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      cassandra-net:
        aliases:
          - cassandra-node2
    depends_on:
      - cassandra-node1

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      cassandra-net:
        aliases:
          - cassandra-node3
    depends_on:
      - cassandra-node1

networks:
  cassandra-net:
    driver: bridge
